source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UIColor-Hex-Swift_Example', :exclusive => true do
  pod "UIColor-Hex-Swift", :path => "../"
end

target 'UIColor-Hex-Swift_Tests', :exclusive => true do
  pod "UIColor-Hex-Swift", :path => "../"

  
end
